my_project\settings\
my_project\settings\__init__.py
my_project\settings\dev.py
my_project\settings\prod.py
my_project\mainapp\
my_project\mainapp\__init__.py
my_project\mainapp\models.py
my_project\mainapp\views.py
my_project\mainapp\templates\mainapp
my_project\mainapp\templates\mainapp\base.html
my_project\mainapp\templates\mainapp\index.html
my_project\authapp\
my_project\authapp\__init__.py
my_project\authapp\models.py
my_project\authapp\views.py
my_project\authapp\templates\authapp\
my_project\authapp\templates\authapp\base.html
my_project\authapp\templates\authapp\index.html